server:
  http:
    host: "localhost" # Хост для HTTP-сервера
    port: 8080        # Порт для HTTP-сервера

database:
  host: "postgres"      # Хост базы данных
  port: 5432             # Порт базы данных
  user: "admin"          # Имя пользователя для базы данных
  password: "normalniy"  # Пароль для подключения
  dbname: "todolist_db"  # Имя базы данных
  sslmode: "disable"     # Режим SSL
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5

redis:
  address: "localhost:6379" # Адрес вашего Redis сервера
  password: ""              # Пароль, если есть
  db: 0                     # Номер базы данных Redis

ratelimiter:
  enabled: true
  limit: 100
  windowSeconds: 60
  errorMessage: "Rate limit exceeded, please try again later."

jwt_secret: "super_secret_key_123"